---
- name: Ensure erlang is installed.
  package:
    name: erlang
    state: present

- name: Add packagecloud GPG key.
  rpm_key:
    key: "https://packagecloud.io/gpg.key"
    state: present
  environment:
    http_proxy: "http://{{ proxy.hostname  | default('') }}:{{ proxy.port | default('') }}"
    https_proxy: "http://{{ proxy.hostname | default('') }}:{{ proxy.port | default('') }}"

- name: Download RabbitMQ package.
  get_url:
    url: "{{ rabbitmq_rpm_url }}"
    dest: "/tmp/{{ rabbitmq_rpm }}"
  environment:
    http_proxy: "http://{{ proxy.hostname }}:{{ proxy.port }}"
    https_proxy: "http://{{ proxy.hostname }}:{{ proxy.port }}"

- name: Ensure RabbitMQ is installed.
  yum:
    name: "/tmp/{{ rabbitmq_rpm }}"
    state: "present"
